<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sungkyun Cho">
<meta name="dcterms.date" content="2024-12-16">

<title>Chapter 19. Latent Means in SEM –  CHA Statistics II in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../contents/chap21.html" rel="next">
<link href="../contents/chap18.html" rel="prev">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/all.css" rel="stylesheet">
<link href="../site_libs/quarto-contrib/fontawesome6-0.1.0/latex-fontsize.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<meta property="og:title" content="Chapter 19. Latent Means in SEM –  CHA Statistics II in R">
<meta property="og:description" content="Multiple Regression and Beyond (3e) by Timothy Z. Keith">
<meta property="og:site_name" content="CHA Statistics II in R">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <a class="flex-grow-1 no-decor" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
          <h1 class="quarto-secondary-nav-title">Chapter 19. Latent Means in SEM</h1>
        </a>     
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../"><i class="fa-solid fa-chart-bar" aria-label="chart-bar"></i> CHA Statistics II in R</a> 
    </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Welcome</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/notice.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Notice</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">R tutorial</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/setup.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Setup</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/baser.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Base R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tidyverse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/import.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Import</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/cleaning.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Cleaning</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/visualize.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Visualize</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/setup2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Packages for SEM</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Keith’s</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../contents/chap12.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Path Modeling</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/interaction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Interactions</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/chap13.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Path Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/chap16.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Factor Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/chap17.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Latent Variable SEM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/chap18.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multigroup Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/chap19.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Latent Means</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/chap21.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Latent Growth Models</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/chap22.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Latent Interactions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/diagnostics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Diagnostics</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/exercises.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercises</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/ml.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ML Estimation</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/equations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SEM Equations</span></a>
  </div>
</li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Kline’s</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="../contents/Kline/composite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Composite</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/Kline/kchap16-1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reflective</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/Kline/kchap16-2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Composite: Formative</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/Kline/kchap16-3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Composite: PLS-PM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/Kline/kchap16-4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Composite: HO</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../contents/Kline/kchap21.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Latent Growth Curve</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="px-0"><hr class="sidebar-divider hi "></li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Communicate</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="https://docs.google.com/document/d/1OQ1D7d4MxEfMZmo_FLj29rGWqvWADKmGc_QD9g5h_ho/edit?usp=sharing" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ask</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sem의-평균-구조-mean-structure" id="toc-sem의-평균-구조-mean-structure" class="nav-link active" data-scroll-target="#sem의-평균-구조-mean-structure">SEM의 평균 구조 (Mean Structure)</a>
  <ul>
  <li><a href="#single-group-sem-models" id="toc-single-group-sem-models" class="nav-link" data-scroll-target="#single-group-sem-models">Single Group SEM Models</a></li>
  <li><a href="#잠재-평균-간의-차이를-검정하는-두-가지-방법" id="toc-잠재-평균-간의-차이를-검정하는-두-가지-방법" class="nav-link" data-scroll-target="#잠재-평균-간의-차이를-검정하는-두-가지-방법">잠재 평균 간의 차이를 검정하는 두 가지 방법</a></li>
  </ul></li>
  <li><a href="#예제-최면과-열감" id="toc-예제-최면과-열감" class="nav-link" data-scroll-target="#예제-최면과-열감">예제: 최면과 열감</a>
  <ul>
  <li><a href="#single-groupdummy-variable-approach" id="toc-single-groupdummy-variable-approach" class="nav-link" data-scroll-target="#single-groupdummy-variable-approach">Single Group/Dummy Variable Approach</a>
  <ul class="collapse">
  <li><a href="#효과의-유의성-검정" id="toc-효과의-유의성-검정" class="nav-link" data-scroll-target="#효과의-유의성-검정">효과의 유의성 검정</a></li>
  </ul></li>
  <li><a href="#multigroup-analysis" id="toc-multigroup-analysis" class="nav-link" data-scroll-target="#multigroup-analysis">Multigroup Analysis</a>
  <ul class="collapse">
  <li><a href="#initial-model" id="toc-initial-model" class="nav-link" data-scroll-target="#initial-model">Initial Model</a></li>
  <li><a href="#무선-할당의-적절성-pretests-differ" id="toc-무선-할당의-적절성-pretests-differ" class="nav-link" data-scroll-target="#무선-할당의-적절성-pretests-differ">무선 할당의 적절성 (Pretests Differ)</a></li>
  <li><a href="#두-방식의-비교-test-assumptions" id="toc-두-방식의-비교-test-assumptions" class="nav-link" data-scroll-target="#두-방식의-비교-test-assumptions">두 방식의 비교 (Test Assumptions)</a>
  <ul class="collapse">
  <li><a href="#slopes-vary" id="toc-slopes-vary" class="nav-link" data-scroll-target="#slopes-vary">Slopes Vary</a></li>
  </ul></li>
  <li><a href="#initial-model-revised" id="toc-initial-model-revised" class="nav-link" data-scroll-target="#initial-model-revised">Initial Model revised</a></li>
  <li><a href="#효과에-대한-재검증" id="toc-효과에-대한-재검증" class="nav-link" data-scroll-target="#효과에-대한-재검증">효과에 대한 재검증</a>
  <ul class="collapse">
  <li><a href="#no-main-effect" id="toc-no-main-effect" class="nav-link" data-scroll-target="#no-main-effect">No Main Effect</a></li>
  <li><a href="#no-interaction-effect" id="toc-no-interaction-effect" class="nav-link" data-scroll-target="#no-interaction-effect">No Interaction Effect</a></li>
  </ul></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block">Chapter 19. Latent Means in SEM</h1>
<p class="subtitle lead">Multiple Regression and Beyond (3e) by Timothy Z. Keith</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sungkyun Cho </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 16, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div id="cell-1" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="1">
<details class="code-fold">
<summary>Load libraries</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lavaan)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(semTools)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(manymome)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="sem의-평균-구조-mean-structure" class="level1">
<h1>SEM의 평균 구조 (Mean Structure)</h1>
<p>예를 들어, 잠재변수 <span class="math inline">\(\xi\)</span>가 잠재변수 <span class="math inline">\(\eta\)</span>에 영향을 주는 모형에 대해,</p>
<div class="columns">
<div class="column" style="width:50%;">
<p>Structural model:<br>
<span class="math inline">\(\eta = \alpha + \gamma*\xi + \zeta\)</span></p>
<p>Measurement model:<br>
<span class="math inline">\(X_1 = \nu_{X_1} + \xi + \delta_1\)</span><br>
<span class="math inline">\(X_2 = \nu_{X_2} + \lambda_{2} *\xi + \delta_2\)</span></p>
<p><span class="math inline">\(Y_1 = \nu_{Y_1} + \eta + \epsilon_1\)</span><br>
<span class="math inline">\(Y_2 = \nu_{Y_2} + \lambda_{4}* \eta + \epsilon_2\)</span></p>
<p>(회귀계수 <span class="math inline">\(\lambda\)</span>: factor loading, 요인부하량, <span class="math inline">\(\alpha, \nu\)</span>: 절편)</p>
</div><div class="column" style="width:50%;">
<p><img src="images/mean-structure.png" class="img-fluid" width="400"></p>
</div>
</div>
<p>각 변수의 평균들은 <span class="math inline">\(\xi\)</span>의 평균 <span class="math inline">\(E(\xi) = m\)</span>이라 하면,<br>
<span class="math inline">\(E(\eta) = \alpha + \gamma*m\)</span>,<br>
<span class="math inline">\(E(X_1) = \nu_{X_1} + m\)</span>, &nbsp;<span class="math inline">\(E(X_2) = \nu_{X_2} + \lambda_{2}*m\)</span>,<br>
<span class="math inline">\(E(Y_1) = \nu_{Y_1} + \alpha + \gamma*m\)</span>, &nbsp;<span class="math inline">\(E(Y_2) = \nu_{Y_2} + \lambda_{4}*(\alpha + \gamma*m)\)</span></p>
<p>새로운 파라미터 <span class="math inline">\(m, \alpha, \nu_{X_1}, \nu_{X_2}, \nu_{Y_1}, \nu_{Y_2}\)</span>를 추정하려면, 6개의 정보가 더 필요하나 변수 4개의 평균 정보만 추가되므로 2개의 파라미터의 제약이 필요함.</p>
<ul>
<li>잠재변수들의 평균을 0으로 설정: <span class="math inline">\(E(\xi) = 0, ~\alpha = 0\)</span>으로 설정; 이때, <span class="math inline">\(E(\nu) = 0\)</span>이 됨</li>
<li>잠재변수들의 원점(0)의 위치를 각각 <span class="math inline">\(X_1\)</span>, <span class="math inline">\(Y_1\)</span>과 동일하게 설정
<ul>
<li>절편을 0으로 고정하면 됨 (잠재변수의 scale은 이미 각각 <span class="math inline">\(X_1, Y_1\)</span>으로 설정되어 있음)</li>
<li><span class="math inline">\(\nu_{X_1} = 0\)</span>; 이때 <span class="math inline">\(E(X_1) = E(\xi)\)</span>, 즉 잠재변수 <span class="math inline">\(\xi\)</span>의 평균이 <span class="math inline">\(X_1\)</span>의 평균과 동일하게 됨</li>
<li><span class="math inline">\(\nu_{Y_1} = 0\)</span>; 이때 <span class="math inline">\(E(Y_1) = E(\eta)\)</span>이 됨, 즉 잠재변수 <span class="math inline">\(\eta\)</span>의 평균이 <span class="math inline">\(Y_1\)</span>의 평균과 동일하게 됨</li>
</ul></li>
</ul>
<p>Multi-group SEM에서 그룹 간에 절편에 대한 동일성을 가정하면, identified 될 수 있음.</p>
<div class="callout callout-style-simple callout-note">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>변수 <span class="math inline">\(X\)</span>의 평균의 의미: 예측변수 <span class="math inline">\(I=(1, 1, ..., 1)\)</span>에 대한 회귀계수인 절편; <code>lm(y ~ 1)</code><br>
절편(intercept)을 통해 평균(mean)을 추정하게 되고<br>
선형함수에 의해 <span class="math inline">\(X\)</span>(들)의 평균(벡터)은 <span class="math inline">\(Y\)</span>의 평균으로 예측됨!<br>
Latent의 평균은 보통 0으로 설정하므로, factor(latent)의 절편은 곧 indicator의 평균이 됨.</p>
</div>
</div>
</div>
<p>파라미터인 절편의 갯수가 늘어나는 만큼 평균에 대한 정보도 늘어나기 때문에,<br>
평균 구조(mean structure)를 추정하더라도 모형의 자유도나 적합도, 모수 등에 변화는 없음.</p>
<p>SEM diagram에서의 표시</p>
<p><img src="images/fig19-2.png" class="img-fluid" width="600"></p>
<p><img src="images/fig19-3.png" class="img-fluid" width="680"> <img src="images/fig19-4.png" class="img-fluid" width="680"></p>
<p>예를 들어,<br>
<img src="images/kline-fig9-1.png" class="img-fluid" width="600"></p>
<div style="line-height: 1.5em; font-size: .8em">
<p>FIGURE 9.1. Recursive path model of illness with unstandardized parameters for the covariance structure and the mean structure. Estimates for the mean structure are shown in boldface. Values for exercise and hardy (exogenous variables) are means, and values for fitness, stress, and illness (endogenous variables) are intercepts.</p>
<p><em>Source: Kline, R. B. (2023). Principles and practice of structural equation modeling (5e)</em></p>
</div>
<div id="cell-4" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="3">
<details class="code-fold">
<summary>Load data</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>hw_mean <span class="ot">&lt;-</span> haven<span class="sc">::</span><span class="fu">read_sav</span>(<span class="st">"data/chap 19 latent means/Homework means.sav"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>가령, 다음과 같은 모형에 대한 절편을 포함한 파라미터를 추정한다면,</p>
<ul>
<li>기본적으로 잠재변수의 평균은 0으로 설정; default</li>
<li>Indicator에 대한 절편을 0으로 고정하고, 잠재변수의 평균을 추정하려면 직접 지정해야 함</li>
</ul>
<p><img src="images/hw-mean-structure.png" class="img-fluid" width="500"></p>
<div id="cell-6" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="4">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>intercept_model <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="st">  Grades =~ eng92 + math92 + sci92 + soc92</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="st">  HW =~ f2s25f2 + f1s36a2</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="st">  Grades ~ HW</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>intercept_fit <span class="ot">&lt;-</span> <span class="fu">sem</span>(intercept_model, <span class="at">data =</span> hw_mean,  <span class="at">meanstructure =</span> <span class="cn">TRUE</span>)</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(intercept_fit, <span class="at">what =</span> <span class="st">"estimates"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$lambda
        Grades    HW
eng92    1.000 0.000
math92   0.882 0.000
sci92    0.970 0.000
soc92    1.032 0.000
f2s25f2  0.000 1.000
f1s36a2  0.000 1.049

$theta
        eng92 math92 sci92 soc92 f2s252 f1s362
eng92   1.052                                 
math92  0.000  2.366                          
sci92   0.000  0.000 1.494                    
soc92   0.000  0.000 0.000 1.330              
f2s25f2 0.000  0.000 0.000 0.000  2.538       
f1s36a2 0.000  0.000 0.000 0.000  0.000  1.407

$psi
       Grades    HW
Grades  3.671      
HW      0.000 1.278

$beta
       Grades    HW
Grades      0 0.958
HW          0 0.000

$nu
        intrcp
eng92    6.512
math92   5.842
sci92    6.163
soc92    6.657
f2s25f2  3.410
f1s36a2  2.584

$alpha
       intrcp
Grades      0
HW          0
</code></pre>
</div>
</div>
<div id="cell-7" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="5">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(intercept_fit) <span class="sc">|&gt;</span> <span class="fu">subset</span>(op <span class="sc">==</span> <span class="st">"~1"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op rhs   est    se      z pvalue ci.lower ci.upper
16   eng92 ~1     6.512 0.082 79.004      0    6.350    6.673
17  math92 ~1     5.842 0.084 69.495      0    5.677    6.006
18   sci92 ~1     6.163 0.084 73.804      0    6.000    6.327
19   soc92 ~1     6.657 0.086 76.961      0    6.487    6.826
20 f2s25f2 ~1     3.410 0.066 51.434      0    3.280    3.540
21 f1s36a2 ~1     2.584 0.057 45.382      0    2.472    2.696
22  Grades ~1     0.000 0.000     NA     NA    0.000    0.000
23      HW ~1     0.000 0.000     NA     NA    0.000    0.000</code></pre>
</div>
</div>
<div id="cell-8" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="6">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(intercept_fit, </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.measures =</span> <span class="cn">FALSE</span>,</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">standardized =</span> <span class="cn">TRUE</span>,</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">remove.unused =</span> <span class="cn">FALSE</span>, <span class="co"># keep the unused parameters</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 40 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        19

                                                  Used       Total
  Number of observations                           868        1000

Model Test User Model:
                                                      
  Test statistic                                20.993
  Degrees of freedom                                 8
  P-value (Chi-square)                           0.007

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Grades =~                                                             
    eng92             1.000                               2.201    0.906
    math92            0.882    0.029   30.161    0.000    1.941    0.784
    sci92             0.970    0.026   36.828    0.000    2.135    0.868
    soc92             1.032    0.027   38.924    0.000    2.272    0.892
  HW =~                                                                 
    f2s25f2           1.000                               1.130    0.579
    f1s36a2           1.049    0.130    8.089    0.000    1.186    0.707

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Grades ~                                                              
    HW                0.958    0.108    8.873    0.000    0.492    0.492

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .eng92             6.512    0.082   79.004    0.000    6.512    2.682
   .math92            5.842    0.084   69.495    0.000    5.842    2.359
   .sci92             6.163    0.084   73.804    0.000    6.163    2.505
   .soc92             6.657    0.086   76.961    0.000    6.657    2.612
   .f2s25f2           3.410    0.066   51.434    0.000    3.410    1.746
   .f1s36a2           2.584    0.057   45.382    0.000    2.584    1.540
   .Grades            0.000                               0.000    0.000
    HW                0.000                               0.000    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .eng92             1.052    0.080   13.149    0.000    1.052    0.178
   .math92            2.366    0.130   18.271    0.000    2.366    0.386
   .sci92             1.494    0.095   15.780    0.000    1.494    0.247
   .soc92             1.330    0.093   14.324    0.000    1.330    0.205
   .f2s25f2           2.538    0.195   13.033    0.000    2.538    0.665
   .f1s36a2           1.407    0.180    7.798    0.000    1.407    0.500
   .Grades            3.671    0.261   14.082    0.000    0.758    0.758
    HW                1.278    0.204    6.252    0.000    1.000    1.000
</code></pre>
</div>
</div>
<p><strong>Indicator의 대한 절편을 0으로 고정하고, 잠재변수의 평균을 추정하려면 직접 지정!</strong></p>
<div id="cell-10" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="7">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>intercept_model2 <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="st">  Grades =~ eng92 + math92 + sci92 + soc92</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="st">  HW =~ f2s25f2 + f1s36a2</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="st">  Grades ~ HW</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="st">  # specify the intercepts</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="st">  Grades ~ 1</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="st">  HW ~ 1</span></span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a><span class="st">  eng92 ~ 0*1</span></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="st">  f2s25f2 ~ 0*1</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>intercept_fit2 <span class="ot">&lt;-</span> <span class="fu">sem</span>(intercept_model2, <span class="at">data =</span> hw_mean,  <span class="at">meanstructure =</span> <span class="cn">TRUE</span>)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="fu">inspect</span>(intercept_fit2, <span class="at">what =</span> <span class="st">"estimates"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$lambda
        Grades    HW
eng92    1.000 0.000
math92   0.882 0.000
sci92    0.970 0.000
soc92    1.032 0.000
f2s25f2  0.000 1.000
f1s36a2  0.000 1.049

$theta
        eng92 math92 sci92 soc92 f2s252 f1s362
eng92   1.052                                 
math92  0.000  2.366                          
sci92   0.000  0.000 1.494                    
soc92   0.000  0.000 0.000 1.330              
f2s25f2 0.000  0.000 0.000 0.000  2.538       
f1s36a2 0.000  0.000 0.000 0.000  0.000  1.407

$psi
       Grades    HW
Grades  3.671      
HW      0.000 1.278

$beta
       Grades    HW
Grades      0 0.958
HW          0 0.000

$nu
        intrcp
eng92    0.000
math92   0.100
sci92   -0.154
soc92   -0.066
f2s25f2  0.000
f1s36a2 -0.995

$alpha
       intrcp
Grades  3.244
HW      3.410
</code></pre>
</div>
</div>
<div id="cell-11" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="8">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(intercept_fit2, </span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.measures =</span> <span class="cn">FALSE</span>,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">standardized =</span> <span class="cn">TRUE</span>,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">remove.unused =</span> <span class="cn">FALSE</span>, <span class="co"># keep the unused parameters</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 63 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        19

                                                  Used       Total
  Number of observations                           868        1000

Model Test User Model:
                                                      
  Test statistic                                20.993
  Degrees of freedom                                 8
  P-value (Chi-square)                           0.007

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Grades =~                                                             
    eng92             1.000                               2.201    0.906
    math92            0.882    0.029   30.161    0.000    1.941    0.784
    sci92             0.970    0.026   36.828    0.000    2.135    0.868
    soc92             1.032    0.027   38.924    0.000    2.272    0.892
  HW =~                                                                 
    f2s25f2           1.000                               1.130    0.579
    f1s36a2           1.049    0.130    8.089    0.000    1.186    0.707

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Grades ~                                                              
    HW                0.958    0.108    8.873    0.000    0.492    0.492

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .Grades            3.244    0.379    8.555    0.000    1.474    1.474
    HW                3.410    0.066   51.434    0.000    3.017    3.017
   .eng92             0.000                               0.000    0.000
   .f2s25f2           0.000                               0.000    0.000
   .math92            0.100    0.200    0.500    0.617    0.100    0.040
   .sci92            -0.154    0.180   -0.857    0.392   -0.154   -0.063
   .soc92            -0.066    0.181   -0.367    0.714   -0.066   -0.026
   .f1s36a2          -0.995    0.448   -2.221    0.026   -0.995   -0.593

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .eng92             1.052    0.080   13.149    0.000    1.052    0.178
   .math92            2.366    0.130   18.271    0.000    2.366    0.386
   .sci92             1.494    0.095   15.780    0.000    1.494    0.247
   .soc92             1.330    0.093   14.324    0.000    1.330    0.205
   .f2s25f2           2.538    0.195   13.033    0.000    2.538    0.665
   .f1s36a2           1.407    0.180    7.798    0.000    1.407    0.500
   .Grades            3.671    0.261   14.082    0.000    0.758    0.758
    HW                1.278    0.204    6.252    0.000    1.000    1.000
</code></pre>
</div>
</div>
<section id="single-group-sem-models" class="level2">
<h2 class="anchored" data-anchor-id="single-group-sem-models">Single Group SEM Models</h2>
<p>Estimation of Means and Intercepts in Single Group SEM Models<br>
<img src="images/fig19-8.png" class="img-fluid" width="700"></p>
<div id="cell-13" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="9">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>hw_model <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="st">  Famback =~ parocc + byfaminc + bypared</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="st">  Prevach =~ bytxrstd + bytxmstd + bytxsstd + bytxhstd</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="st">  HW =~ f2s25f2 + f1s36a2</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="st">  Grades =~ eng92 + math92 + sci92 + soc92</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="st">  bytxrstd ~~ eng92</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="st">  bytxmstd ~~ math92</span></span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="st">  bytxsstd ~~ sci92</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="st">  bytxhstd ~~ soc92</span></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a><span class="st">  Prevach ~ Famback</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a><span class="st">  Grades ~ Prevach + HW</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a><span class="st">  HW ~ Prevach + Famback</span></span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>sem_fit <span class="ot">&lt;-</span> <span class="fu">sem</span>(hw_model,</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> hw_mean,</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">meanstructure =</span> <span class="cn">TRUE</span>,</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">missing =</span> <span class="st">"FIML"</span>  <span class="co"># for mising data</span></span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(sem_fit, <span class="at">standardized =</span> <span class="cn">TRUE</span>, <span class="at">fit.measures =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 171 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        48

  Number of observations                          1000
  Number of missing patterns                        42

Model Test User Model:
                                                      
  Test statistic                               113.358
  Degrees of freedom                                56
  P-value (Chi-square)                           0.000

Model Test Baseline Model:

  Test statistic                              7792.886
  Degrees of freedom                                78
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.993
  Tucker-Lewis Index (TLI)                       0.990
                                                      
  Robust Comparative Fit Index (CFI)             0.993
  Robust Tucker-Lewis Index (TLI)                0.990

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)             -32104.831
  Loglikelihood unrestricted model (H1)             NA
                                                      
  Akaike (AIC)                               64305.662
  Bayesian (BIC)                             64541.235
  Sample-size adjusted Bayesian (SABIC)      64388.784

Root Mean Square Error of Approximation:

  RMSEA                                          0.032
  90 Percent confidence interval - lower         0.023
  90 Percent confidence interval - upper         0.040
  P-value H_0: RMSEA &lt;= 0.050                    1.000
  P-value H_0: RMSEA &gt;= 0.080                    0.000
                                                      
  Robust RMSEA                                   0.032
  90 Percent confidence interval - lower         0.023
  90 Percent confidence interval - upper         0.041
  P-value H_0: Robust RMSEA &lt;= 0.050             1.000
  P-value H_0: Robust RMSEA &gt;= 0.080             0.000

Standardized Root Mean Square Residual:

  SRMR                                           0.023

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Observed
  Observed information based on                Hessian

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Famback =~                                                            
    parocc            1.000                              15.210    0.710
    byfaminc          0.124    0.006   19.348    0.000    1.891    0.728
    bypared           0.069    0.003   20.632    0.000    1.049    0.834
  Prevach =~                                                            
    bytxrstd          1.000                               8.532    0.852
    bytxmstd          0.988    0.030   32.651    0.000    8.432    0.853
    bytxsstd          0.960    0.031   30.702    0.000    8.189    0.819
    bytxhstd          0.942    0.030   31.597    0.000    8.039    0.830
  HW =~                                                                 
    f2s25f2           1.000                               1.171    0.592
    f1s36a2           0.994    0.103    9.671    0.000    1.164    0.688
  Grades =~                                                             
    eng92             1.000                               2.436    0.915
    math92            0.876    0.025   34.958    0.000    2.135    0.812
    sci92             0.961    0.023   41.780    0.000    2.341    0.884
    soc92             1.049    0.023   45.416    0.000    2.555    0.908

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  Prevach ~                                                             
    Famback           0.325    0.022   14.540    0.000    0.579    0.579
  Grades ~                                                              
    Prevach           0.140    0.011   12.973    0.000    0.490    0.490
    HW                0.655    0.101    6.491    0.000    0.315    0.315
  HW ~                                                                  
    Prevach           0.045    0.008    5.612    0.000    0.331    0.331
    Famback           0.018    0.005    3.986    0.000    0.235    0.235

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
 .bytxrstd ~~                                                           
   .eng92             0.486    0.256    1.900    0.057    0.486    0.086
 .bytxmstd ~~                                                           
   .math92            1.573    0.320    4.915    0.000    1.573    0.199
 .bytxsstd ~~                                                           
   .sci92             0.459    0.294    1.563    0.118    0.459    0.064
 .bytxhstd ~~                                                           
   .soc92             0.266    0.278    0.956    0.339    0.266    0.042

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .parocc           51.388    0.679   75.669    0.000   51.388    2.400
   .byfaminc          9.841    0.083  118.414    0.000    9.841    3.792
   .bypared           3.128    0.040   78.568    0.000    3.128    2.485
   .bytxrstd         51.257    0.320  160.386    0.000   51.257    5.120
   .bytxmstd         51.493    0.316  163.072    0.000   51.493    5.206
   .bytxsstd         51.179    0.320  160.149    0.000   51.179    5.117
   .bytxhstd         51.373    0.310  165.931    0.000   51.373    5.302
   .f2s25f2           3.280    0.066   49.942    0.000    3.280    1.659
   .f1s36a2           2.481    0.055   45.366    0.000    2.481    1.465
   .eng92             6.074    0.084   71.892    0.000    6.074    2.281
   .math92            5.482    0.083   65.676    0.000    5.482    2.086
   .sci92             5.770    0.084   68.653    0.000    5.770    2.177
   .soc92             6.207    0.089   69.614    0.000    6.207    2.207

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .parocc          227.271   13.266   17.132    0.000  227.271    0.496
   .byfaminc          3.161    0.198   15.973    0.000    3.161    0.469
   .bypared           0.483    0.044   10.967    0.000    0.483    0.305
   .bytxrstd         27.413    1.704   16.091    0.000   27.413    0.274
   .bytxmstd         26.728    1.669   16.017    0.000   26.728    0.273
   .bytxsstd         32.977    1.881   17.536    0.000   32.977    0.330
   .bytxhstd         29.242    1.709   17.107    0.000   29.242    0.312
   .f2s25f2           2.537    0.178   14.290    0.000    2.537    0.649
   .f1s36a2           1.510    0.149   10.158    0.000    1.510    0.527
   .eng92             1.155    0.080   14.479    0.000    1.155    0.163
   .math92            2.349    0.122   19.249    0.000    2.349    0.340
   .sci92             1.541    0.092   16.744    0.000    1.541    0.219
   .soc92             1.383    0.091   15.197    0.000    1.383    0.175
    Famback         231.337   19.948   11.597    0.000    1.000    1.000
   .Prevach          48.379    3.317   14.583    0.000    0.665    0.665
   .HW                1.021    0.154    6.644    0.000    0.745    0.745
   .Grades            3.063    0.200   15.324    0.000    0.516    0.516
</code></pre>
</div>
</div>
</section>
<section id="잠재-평균-간의-차이를-검정하는-두-가지-방법" class="level2">
<h2 class="anchored" data-anchor-id="잠재-평균-간의-차이를-검정하는-두-가지-방법">잠재 평균 간의 차이를 검정하는 두 가지 방법</h2>
<ul>
<li>더미 변수의 회귀계수를 통해 평균의 차이를 추정하는 방법: 예. 성별에 대한 주효과에 대한 검증<br>
<img src="images/fig19-11.png" class="img-fluid" width="600"></li>
<li>Multigroup SEM을 통해 추정하는 방법: 예. 성별과 과제의 상호작용 효과에 대한 검증<br>
<img src="images/fig19-12.png" class="img-fluid"><br>
</li>
<li>잠재변수의 intercept를 추정하는 방법: 주효과와 상호작용 효과를 동시에 추정할 수 있음<br>
(MG-MACS; multi-group mean and covariance structures)<br>
<img src="images/fig19-13.png" class="img-fluid"></li>
</ul>
</section>
</section>
<section id="예제-최면과-열감" class="level1">
<h1>예제: 최면과 열감</h1>
<p><em><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC2652097/">Elkins et. al.&nbsp;(2008).</a> Randomized trial of a hypnosis intervention for treatment of hot flashes among breast cancer survivors. Journal of Clinical Oncology, 26(31), 5022-5026.</em></p>
<ul>
<li>화학요법의 일반적인 부작용으로 폐경과 화끈거림이 발생</li>
<li>최면을 사용해 유방암 생존자의 화끈거림(hot flash)을 조절하려는 치료</li>
<li>60명 여성을 무작위 배정: 최면 치료 그룹(5주) vs.&nbsp;통제 그룹</li>
<li>사전-사후 검사
<ul>
<li>HF: 열감의 빈도와 강도의 조합</li>
<li>int: 열감이 일상에 지장을 주는 정도</li>
</ul></li>
</ul>
<div id="cell-20" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="14">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load the dataset</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>hotflash <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">"data/chap 19 latent means/hot flash simulated.sav"</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># make a grouping variable as a factor</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>hotflash <span class="ot">&lt;-</span> hotflash <span class="sc">|&gt;</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">g =</span> <span class="fu">factor</span>(Group, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"control"</span>, <span class="st">"treatment"</span>)))</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>hotflash <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 96 × 6
  Group                       HF1   HF2  int1  int2 g        
  &lt;dbl+lbl&gt;                 &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;fct&gt;    
1 0 [Control]               33.4  32.7     64    38 control  
2 1 [Hypnosis Intervention] 25.5  12.7     52     5 treatment
3 1 [Hypnosis Intervention] 11.0   7.60     9     2 treatment
4 1 [Hypnosis Intervention]  8.05  4.05    13     6 treatment
5 0 [Control]               13.2   4.34    61    36 control  
6 0 [Control]                9.89  8.89    15    34 control  
# ℹ 90 more rows</code></pre>
</div>
</div>
<p><code>ggstatsplot</code>을 이용해 시각화</p>
<div id="cell-22" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="15">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="chap19_files/figure-html/cell-16-output-1.png" width="700" height="350" class="figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="chap19_files/figure-html/cell-16-output-2.png" width="700" height="350" class="figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="single-groupdummy-variable-approach" class="level2">
<h2 class="anchored" data-anchor-id="single-groupdummy-variable-approach">Single Group/Dummy Variable Approach</h2>
<p>모형에 대한 가정 검토</p>
<p><img src="images/fig19-16.png" class="img-fluid" width="700"></p>
<div id="cell-24" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="16">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>hotflash_model <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre =~ int1 + HF1</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post =~ int2 + HF2</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post ~ hf_pre + Group  # Group: numeric variable!</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="st">  HF1 ~~ HF2</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a><span class="st">  int1 ~~ int2</span></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>hotflash_fit <span class="ot">&lt;-</span> <span class="fu">sem</span>(hotflash_model, <span class="at">data =</span> hotflash)</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hotflash_fit, </span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>  <span class="at">standardized =</span> <span class="st">"std.nox"</span>, <span class="co"># dummy 변수에 대해서는 표준화하지 않기 위함</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.measures =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 161 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        12

  Number of observations                            96

Model Test User Model:
                                                      
  Test statistic                                 3.501
  Degrees of freedom                                 2
  P-value (Chi-square)                           0.174

Model Test Baseline Model:

  Test statistic                               244.790
  Degrees of freedom                                10
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.994
  Tucker-Lewis Index (TLI)                       0.968

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)              -1466.241
  Loglikelihood unrestricted model (H1)             NA
                                                      
  Akaike (AIC)                                2956.482
  Bayesian (BIC)                              2987.254
  Sample-size adjusted Bayesian (SABIC)       2949.365

Root Mean Square Error of Approximation:

  RMSEA                                          0.088
  90 Percent confidence interval - lower         0.000
  90 Percent confidence interval - upper         0.239
  P-value H_0: RMSEA &lt;= 0.050                    0.245
  P-value H_0: RMSEA &gt;= 0.080                    0.649

Standardized Root Mean Square Residual:

  SRMR                                           0.082

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)  Std.nox
  hf_pre =~                                                    
    int1              1.000                               0.932
    HF1               0.260    0.112    2.323    0.020    0.439
  hf_post =~                                                   
    int2              1.000                               0.927
    HF2               0.310    0.037    8.480    0.000    0.659

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)  Std.nox
  hf_post ~                                                    
    hf_pre            0.487    0.195    2.500    0.012    0.441
    Group           -28.615    3.149   -9.087    0.000   -1.386

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)  Std.nox
 .HF1 ~~                                                       
   .HF2              60.277   10.820    5.571    0.000    0.831
 .int1 ~~                                                      
   .int2            -24.643   55.046   -0.448    0.654   -0.405

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)  Std.nox
   .int1             52.754  179.207    0.294    0.768    0.131
   .HF1              98.604   17.851    5.524    0.000    0.807
   .int2             70.301   51.321    1.370    0.171    0.142
   .HF2              53.415    9.107    5.865    0.000    0.565
    hf_pre          349.972  190.044    1.842    0.066    1.000
   .hf_post         138.752   35.569    3.901    0.000    0.325
</code></pre>
</div>
</div>
<section id="효과의-유의성-검정" class="level3">
<h3 class="anchored" data-anchor-id="효과의-유의성-검정">효과의 유의성 검정</h3>
<ul>
<li>무선할당이 적절히 이루어졌는지 확인</li>
<li>최면 치료의 효과가 유의한지 확인</li>
</ul>
<p><img src="images/table19-1.png" class="img-fluid" width="700"></p>
<div id="cell-26" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="17">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># free covariance between pretest and group</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>hotflash_model2 <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre =~ int1 + HF1</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post =~ int2 + HF2</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post ~ hf_pre + Group</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre ~ Group  # free the parameter</span></span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="st">  HF1 ~~ HF2</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="st">  int1 ~~ int2</span></span>
<span id="cb19-11"><a href="#cb19-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-12"><a href="#cb19-12" aria-hidden="true" tabindex="-1"></a><span class="st">  # 또는 hf_pre ~~ Group</span></span>
<span id="cb19-13"><a href="#cb19-13" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb19-14"><a href="#cb19-14" aria-hidden="true" tabindex="-1"></a>hotflash_fit2 <span class="ot">&lt;-</span> <span class="fu">sem</span>(hotflash_model2, <span class="at">data =</span> hotflash)</span>
<span id="cb19-15"><a href="#cb19-15" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(hotflash_fit2, <span class="at">standardized =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> <span class="fu">subset</span>(rhs <span class="sc">==</span> <span class="st">"Group"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op   rhs     est    se      z pvalue ci.lower ci.upper std.lv std.all std.nox
6  hf_post  ~ Group -27.460 3.413 -8.047   0.00  -34.149  -20.771 -1.286  -0.643  -1.286
7   hf_pre  ~ Group  -7.485 3.982 -1.880   0.06  -15.289    0.318 -0.428  -0.214  -0.428
16   Group ~~ Group   0.250 0.000     NA     NA    0.250    0.250  0.250   1.000   0.250</code></pre>
</div>
</div>
<div id="cell-27" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="18">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">lavTestLRT</span>(hotflash_fit2, hotflash_fit) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Chi-Squared Difference Test

              Df    AIC    BIC  Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
hotflash_fit2  1 2955.1 2988.4 0.0881                                        
hotflash_fit   2 2956.5 2987.2 3.5007     3.4126 0.15853       1     0.0647 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1</code></pre>
</div>
</div>
<div id="cell-28" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="19">
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># no effect of group on post-test</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>hotflash_model3 <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre =~ int1 + HF1</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post =~ int2 + HF2</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post ~ hf_pre + 0*Group  # fix the parameter to 0</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre ~ Group  # free the parameter</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="st">  HF1 ~~ HF2</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="st">  int1 ~~ int2</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a>hotflash_fit3 <span class="ot">&lt;-</span> <span class="fu">sem</span>(hotflash_model3, <span class="at">data =</span> hotflash)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-29" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="20">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">compareFit</span>(hotflash_fit3, hotflash_fit2) <span class="sc">|&gt;</span> <span class="fu">summary</span>() <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

              Df    AIC    BIC   Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)    
hotflash_fit2  1 2955.1 2988.4  0.0881                                          
hotflash_fit3  2 2969.2 3000.0 16.2486      16.16 0.39739       1   5.82e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

####################### Model Fit Indices ###########################
                chisq df pvalue rmsea    cfi    tli  srmr       aic       bic
hotflash_fit2   .088†  1   .767 .000† 1.000† 1.039† .009† 2955.070† 2988.406†
hotflash_fit3 16.249   2   .000 .272   .939   .697  .113  2969.230  3000.002 

################## Differences in Fit Indices #######################
                              df rmsea    cfi    tli  srmr   aic    bic
hotflash_fit3 - hotflash_fit2  1 0.272 -0.061 -0.342 0.104 14.16 11.596

The following lavaan models were compared:
    hotflash_fit2
    hotflash_fit3
To view results, assign the compareFit() output to an object and  use the summary() method; see the class?FitDiff help page.</code></pre>
</div>
</div>
</section>
</section>
<section id="multigroup-analysis" class="level2">
<h2 class="anchored" data-anchor-id="multigroup-analysis">Multigroup Analysis</h2>
<p>MG-MACS (Multiple Group Mean and Covariance Structure Analysis) Approach</p>
<section id="initial-model" class="level3">
<h3 class="anchored" data-anchor-id="initial-model">Initial Model</h3>
<p>측정 모형에 대해서:</p>
<ul>
<li>요인부하량이 두 집단이 동일하다고 가정함: 잠재변수가 동일한 metric을 가진 것으로 제약 (집단 간 요인구조에 대한 weak measurement invariance 가정)</li>
<li>요인에 대해서 intercept가 두 집단이 동일하다고 가정함: 잠재변수의 원점(0)이 동일하다고 제약 (strong measurement invariance 가정)</li>
</ul>
<p>구조 모형에 대해서:</p>
<ul>
<li>Pretest 잠재변수에 대해 두 집단의 평균이 모두 0으로 동일하다고 가정; 즉 무선할당이 적절히 이루어졌다고 가정함; test 가능</li>
<li>Posttest 잠재변수에 대해서
<ul>
<li>통제집단에서 intercept:0 고정, 치료집단에서 intercept는 추정함; default</li>
<li>이를 통해 |치료집단 - 통제집단| 차이가 intercept에서 나타남</li>
</ul></li>
</ul>
<p><img src="images/fig19-19-2.png" class="img-fluid" width="800"></p>
<div id="cell-32" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="21">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># initial model</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>hotflash_model_mg <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre =~ int1 + HF1</span></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post =~ int2 + HF2</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post ~ hf_pre</span></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="st">  HF1 ~~ HF2</span></span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="st">  int1 ~~ int2</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre ~ 0*1  # default로 group2에서 intercept를 0으로 고정하지 않음!</span></span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="st">  </span></span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="st">  ### Defaults</span></span>
<span id="cb26-14"><a href="#cb26-14" aria-hidden="true" tabindex="-1"></a><span class="st">  # hf_post ~ c(a1, a2)*1  # 첫번째 집단의 intercept:0, 두번째 집단 intercept는 추정</span></span>
<span id="cb26-15"><a href="#cb26-15" aria-hidden="true" tabindex="-1"></a><span class="st">  # a1 == 0</span></span>
<span id="cb26-16"><a href="#cb26-16" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb26-17"><a href="#cb26-17" aria-hidden="true" tabindex="-1"></a>hotflash_fit_mg <span class="ot">&lt;-</span> <span class="fu">sem</span>(hotflash_model_mg,</span>
<span id="cb26-18"><a href="#cb26-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> hotflash,</span>
<span id="cb26-19"><a href="#cb26-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">meanstructure =</span> <span class="cn">TRUE</span>, <span class="co"># mean structure</span></span>
<span id="cb26-20"><a href="#cb26-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="st">"g"</span>, <span class="co"># factor type</span></span>
<span id="cb26-21"><a href="#cb26-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"loadings"</span>, <span class="st">"intercepts"</span>)</span>
<span id="cb26-22"><a href="#cb26-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb26-23"><a href="#cb26-23" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hotflash_fit_mg, </span>
<span id="cb26-24"><a href="#cb26-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">standardized =</span> <span class="cn">TRUE</span>, </span>
<span id="cb26-25"><a href="#cb26-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">fit.measures =</span> <span class="cn">TRUE</span>,</span>
<span id="cb26-26"><a href="#cb26-26" aria-hidden="true" tabindex="-1"></a>  <span class="at">remove.unused =</span> <span class="cn">FALSE</span>, <span class="co"># keep the unused parameters</span></span>
<span id="cb26-27"><a href="#cb26-27" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 326 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        31
  Number of equality constraints                     6

  Number of observations per group:                   
    control                                         48
    treatment                                       48

Model Test User Model:
                                                      
  Test statistic                                 5.399
  Degrees of freedom                                 3
  P-value (Chi-square)                           0.145
  Test statistic for each group:
    control                                      2.169
    treatment                                    3.229

Model Test Baseline Model:

  Test statistic                               182.941
  Degrees of freedom                                12
  P-value                                        0.000

User Model versus Baseline Model:

  Comparative Fit Index (CFI)                    0.986
  Tucker-Lewis Index (TLI)                       0.944

Loglikelihood and Information Criteria:

  Loglikelihood user model (H0)              -1425.733
  Loglikelihood unrestricted model (H1)      -1423.033
                                                      
  Akaike (AIC)                                2901.465
  Bayesian (BIC)                              2965.574
  Sample-size adjusted Bayesian (SABIC)       2886.638

Root Mean Square Error of Approximation:

  RMSEA                                          0.129
  90 Percent confidence interval - lower         0.000
  90 Percent confidence interval - upper         0.302
  P-value H_0: RMSEA &lt;= 0.050                    0.185
  P-value H_0: RMSEA &gt;= 0.080                    0.751

Standardized Root Mean Square Residual:

  SRMR                                           0.088

Parameter Estimates:

  Standard errors                             Standard
  Information                                 Expected
  Information saturated (h1) model          Structured


Group 1 [control]:

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  hf_pre =~                                                             
    int1              1.000                              16.945    0.792
    HF1     (.p2.)    0.388    0.115    3.388    0.001    6.573    0.607
  hf_post =~                                                            
    int2              1.000                              21.010    0.959
    HF2     (.p4.)    0.312    0.037    8.433    0.000    6.559    0.587

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  hf_post ~                                                             
    hf_pre            1.139    0.274    4.156    0.000    0.919    0.919

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
 .HF1 ~~                                                                
   .HF2              67.058   18.003    3.725    0.000   67.058    0.862
 .int1 ~~                                                               
   .int2            -28.916   98.630   -0.293    0.769  -28.916   -0.355

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
    hf_pre            0.000                               0.000    0.000
   .int1    (.15.)   42.049    2.027   20.742    0.000   42.049    1.966
   .HF1     (.16.)   15.473    1.089   14.206    0.000   15.473    1.429
   .int2    (.17.)   39.131    2.690   14.548    0.000   39.131    1.785
   .HF2     (.18.)   14.044    1.248   11.256    0.000   14.044    1.258
   .hf_post           0.000                               0.000    0.000

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .int1            170.287  124.805    1.364    0.172  170.287    0.372
   .HF1              74.107   19.536    3.793    0.000   74.107    0.632
   .int2             39.030  107.473    0.363    0.716   39.030    0.081
   .HF2              81.674   19.666    4.153    0.000   81.674    0.655
    hf_pre          287.136  148.917    1.928    0.054    1.000    1.000
   .hf_post          68.950   49.956    1.380    0.168    0.156    0.156


Group 2 [treatment]:

Latent Variables:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  hf_pre =~                                                             
    int1              1.000                              10.689    0.567
    HF1     (.p2.)    0.388    0.115    3.388    0.001    4.146    0.384
  hf_post =~                                                            
    int2              1.000                               5.158    0.496
    HF2     (.p4.)    0.312    0.037    8.433    0.000    1.610    0.308

Regressions:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
  hf_post ~                                                             
    hf_pre           -0.456    0.459   -0.993    0.321   -0.944   -0.944

Covariances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
 .HF1 ~~                                                                
   .HF2              47.191   10.578    4.461    0.000   47.191    0.950
 .int1 ~~                                                               
   .int2             44.760   37.540    1.192    0.233   44.760    0.319

Intercepts:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
    hf_pre            0.000                               0.000    0.000
   .int1    (.15.)   42.049    2.027   20.742    0.000   42.049    2.230
   .HF1     (.16.)   15.473    1.089   14.206    0.000   15.473    1.432
   .int2    (.17.)   39.131    2.690   14.548    0.000   39.131    3.764
   .HF2     (.18.)   14.044    1.248   11.256    0.000   14.044    2.684
   .hf_post         -28.439    3.135   -9.071    0.000   -5.513   -5.513

Variances:
                   Estimate  Std.Err  z-value  P(&gt;|z|)   Std.lv  Std.all
   .int1            241.229   74.588    3.234    0.001  241.229    0.679
   .HF1              99.551   23.596    4.219    0.000   99.551    0.853
   .int2             81.492   25.448    3.202    0.001   81.492    0.754
   .HF2              24.780    5.610    4.417    0.000   24.780    0.905
    hf_pre          114.255   70.087    1.630    0.103    1.000    1.000
   .hf_post           2.901   52.283    0.055    0.956    0.109    0.109
</code></pre>
</div>
</div>
<div id="cell-33" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="22">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(hotflash_fit_mg) <span class="sc">|&gt;</span> <span class="fu">subset</span>(op <span class="sc">==</span> <span class="st">"~1"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op rhs block group label     est    se      z pvalue ci.lower ci.upper
8   hf_pre ~1         1     1         0.000 0.000     NA     NA    0.000    0.000
15    int1 ~1         1     1 .p15.  42.049 2.027 20.742      0   38.075   46.022
16     HF1 ~1         1     1 .p16.  15.473 1.089 14.206      0   13.339   17.608
17    int2 ~1         1     1 .p17.  39.131 2.690 14.548      0   33.859   44.403
18     HF2 ~1         1     1 .p18.  14.044 1.248 11.256      0   11.598   16.489
19 hf_post ~1         1     1         0.000 0.000     NA     NA    0.000    0.000
27  hf_pre ~1         2     2         0.000 0.000     NA     NA    0.000    0.000
34    int1 ~1         2     2 .p15.  42.049 2.027 20.742      0   38.075   46.022
35     HF1 ~1         2     2 .p16.  15.473 1.089 14.206      0   13.339   17.608
36    int2 ~1         2     2 .p17.  39.131 2.690 14.548      0   33.859   44.403
37     HF2 ~1         2     2 .p18.  14.044 1.248 11.256      0   11.598   16.489
38 hf_post ~1         2     2       -28.439 3.135 -9.071      0  -34.584  -22.295</code></pre>
</div>
</div>
<div id="cell-34" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="23">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Free parameters 확인</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">parTable</span>(hotflash_fit_mg) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   id     lhs op     rhs user block group free ustart exo label plabel   start     est
1   1  hf_pre =~    int1    1     1     1    0      1   0         .p1.   1.000   1.000
2   2  hf_pre =~     HF1    1     1     1    1     NA   0  .p2.   .p2.   0.388   0.388
3   3 hf_post =~    int2    1     1     1    0      1   0         .p3.   1.000   1.000
4   4 hf_post =~     HF2    1     1     1    2     NA   0  .p4.   .p4.   0.448   0.312
5   5 hf_post  ~  hf_pre    1     1     1    3     NA   0         .p5.   0.000   1.139
6   6     HF1 ~~     HF2    1     1     1    4     NA   0         .p6.   0.000  67.058
7   7    int1 ~~    int2    1     1     1    5     NA   0         .p7.   0.000 -28.916
8   8  hf_pre ~1            1     1     1    0      0   0         .p8.   0.000   0.000
9   9    int1 ~~    int1    0     1     1    6     NA   0         .p9. 224.087 170.287
10 10     HF1 ~~     HF1    0     1     1    7     NA   0        .p10.  57.344  74.107
11 11    int2 ~~    int2    0     1     1    8     NA   0        .p11. 233.573  39.030
12 12     HF2 ~~     HF2    0     1     1    9     NA   0        .p12.  61.474  81.674
13 13  hf_pre ~~  hf_pre    0     1     1   10     NA   0        .p13.   0.050 287.136
14 14 hf_post ~~ hf_post    0     1     1   11     NA   0        .p14.   0.050  68.950
15 15    int1 ~1            0     1     1   12     NA   0 .p15.  .p15.  46.312  42.049
16 16     HF1 ~1            0     1     1   13     NA   0 .p16.  .p16.  17.077  15.473
17 17    int2 ~1            0     1     1   14     NA   0 .p17.  .p17.  42.250  39.131
18 18     HF2 ~1            0     1     1   15     NA   0 .p18.  .p18.  15.508  14.044
19 19 hf_post ~1            0     1     1    0      0   0        .p19.   0.000   0.000
20 20  hf_pre =~    int1    1     2     2    0      1   0        .p20.   1.000   1.000
21 21  hf_pre =~     HF1    1     2     2   16     NA   0  .p2.  .p21.   0.275   0.388
22 22 hf_post =~    int2    1     2     2    0      1   0        .p22.   1.000   1.000
23 23 hf_post =~     HF2    1     2     2   17     NA   0  .p4.  .p23.   0.044   0.312
24 24 hf_post  ~  hf_pre    1     2     2   18     NA   0        .p24.   0.000  -0.456
25 25     HF1 ~~     HF2    1     2     2   19     NA   0        .p25.   0.000  47.191
26 26    int1 ~~    int2    1     2     2   20     NA   0        .p26.   0.000  44.760
27 27  hf_pre ~1            1     2     2    0      0   0        .p27.   0.000   0.000
28 28    int1 ~~    int1    0     2     2   21     NA   0        .p28. 165.271 241.229
29 29     HF1 ~~     HF1    0     2     2   22     NA   0        .p29.  63.038  99.551
30 30    int2 ~~    int2    0     2     2   23     NA   0        .p30.  56.430  81.492
31 31     HF2 ~~     HF2    0     2     2   24     NA   0        .p31.  12.662  24.780
32 32  hf_pre ~~  hf_pre    0     2     2   25     NA   0        .p32.   0.050 114.255
33 33 hf_post ~~ hf_post    0     2     2   26     NA   0        .p33.   0.050   2.901
34 34    int1 ~1            0     2     2   27     NA   0 .p15.  .p34.  39.000  42.049
35 35     HF1 ~1            0     2     2   28     NA   0 .p16.  .p35.  14.396  15.473
36 36    int2 ~1            0     2     2   29     NA   0 .p17.  .p36.  10.875  39.131
37 37     HF2 ~1            0     2     2   30     NA   0 .p18.  .p37.   5.036  14.044
38 38 hf_post ~1            0     2     2   31     NA   0        .p38.   0.000 -28.439
39 39    .p2. ==   .p21.    2     0     0    0     NA   0                0.000   0.000
40 40    .p4. ==   .p23.    2     0     0    0     NA   0                0.000   0.000
41 41   .p15. ==   .p34.    2     0     0    0     NA   0                0.000   0.000
42 42   .p16. ==   .p35.    2     0     0    0     NA   0                0.000   0.000
43 43   .p17. ==   .p36.    2     0     0    0     NA   0                0.000   0.000
44 44   .p18. ==   .p37.    2     0     0    0     NA   0                0.000   0.000
        se
1    0.000
2    0.115
3    0.000
4    0.037
5    0.274
6   18.003
7   98.630
8    0.000
9  124.805
10  19.536
11 107.473
12  19.666
13 148.917
14  49.956
15   2.027
16   1.089
17   2.690
18   1.248
19   0.000
20   0.000
21   0.115
22   0.000
23   0.037
24   0.459
25  10.578
26  37.540
27   0.000
28  74.588
29  23.596
30  25.448
31   5.610
32  70.087
33  52.283
34   2.027
35   1.089
36   2.690
37   1.248
38   3.135
39   0.000
40   0.000
41   0.000
42   0.000
43   0.000
44   0.000</code></pre>
</div>
</div>
<p>실제 평균과 비교해보면,</p>
<ul>
<li>추정된 관찰변수의 평균(intercept)는 잠재변수의 평균(0)에 대한 예측값임.<br>
</li>
<li>위에서는 두 집단 간에 pre-test 잠재변수의 값이 동일하게 0이라고 가정했음.</li>
</ul>
<div id="cell-36" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="24">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>hotflash <span class="sc">|&gt;</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(g) <span class="sc">|&gt;</span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="fu">across</span>(HF1<span class="sc">:</span>int2, mean)) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 5
  g           HF1   HF2  int1  int2
  &lt;fct&gt;     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 control    17.1 15.5   46.3  42.2
2 treatment  14.4  5.04  39    10.9</code></pre>
</div>
</div>
<hr>
<p><strong>모형에 대한 여러 가정들과 효과들을 검증</strong></p>
<p><img src="images/table19-2.png" class="img-fluid" width="700"></p>
<div class="callout callout-style-simple callout-tip">
<div class="callout-body d-flex">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-body-container">
<p>Keith’s Table 19.2에서 RMSEA값은 조정되지 않은 값으로 <span class="math inline">\(\sqrt{2}\)</span>를 곱해야 lavaan/Mplus 결과값과 동일함.</p>
</div>
</div>
</div>
</section>
<section id="무선-할당의-적절성-pretests-differ" class="level3">
<h3 class="anchored" data-anchor-id="무선-할당의-적절성-pretests-differ">무선 할당의 적절성 (Pretests Differ)</h3>
<p>사전 검사에서 두 집단 간의 평균(intercept)이 같다는 가정을 하지 않았을 때,<br>
즉, free the estimate of the intercepts for the pretest latent variables</p>
<div id="cell-39" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="25">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># free pretest intercepts</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>hotflash_model_mg2 <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre =~ int1 + HF1</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post =~ int2 + HF2</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post ~ hf_pre</span></span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-8"><a href="#cb34-8" aria-hidden="true" tabindex="-1"></a><span class="st">  HF1 ~~ HF2</span></span>
<span id="cb34-9"><a href="#cb34-9" aria-hidden="true" tabindex="-1"></a><span class="st">  int1 ~~ int2</span></span>
<span id="cb34-10"><a href="#cb34-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-11"><a href="#cb34-11" aria-hidden="true" tabindex="-1"></a><span class="st">  # hf_pre ~ 0*1 # 제거</span></span>
<span id="cb34-12"><a href="#cb34-12" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb34-13"><a href="#cb34-13" aria-hidden="true" tabindex="-1"></a>hotflash_fit_mg2 <span class="ot">&lt;-</span> <span class="fu">sem</span>(hotflash_model_mg2,</span>
<span id="cb34-14"><a href="#cb34-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> hotflash,</span>
<span id="cb34-15"><a href="#cb34-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">meanstructure =</span> <span class="cn">TRUE</span>,</span>
<span id="cb34-16"><a href="#cb34-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="st">"g"</span>, <span class="co"># factor type</span></span>
<span id="cb34-17"><a href="#cb34-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"loadings"</span>, <span class="st">"intercepts"</span>)</span>
<span id="cb34-18"><a href="#cb34-18" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-40" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="26">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(hotflash_fit_mg2, <span class="at">estimates =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>lavaan 0.6-19 ended normally after 316 iterations

  Estimator                                         ML
  Optimization method                           NLMINB
  Number of model parameters                        32
  Number of equality constraints                     6

  Number of observations per group:                   
    control                                         48
    treatment                                       48

Model Test User Model:
                                                      
  Test statistic                                 1.827
  Degrees of freedom                                 2
  P-value (Chi-square)                           0.401
  Test statistic for each group:
    control                                      0.069
    treatment                                    1.758</code></pre>
</div>
</div>
<div id="cell-41" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="27">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(hotflash_fit_mg2) <span class="sc">|&gt;</span> <span class="fu">subset</span>(op <span class="sc">==</span> <span class="st">"~1"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op rhs block group label     est    se      z pvalue ci.lower ci.upper
14    int1 ~1         1     1 .p14.  46.160 2.931 15.749  0.000   40.415   51.904
15     HF1 ~1         1     1 .p15.  17.176 1.460 11.763  0.000   14.315   20.038
16    int2 ~1         1     1 .p16.  42.265 3.128 13.513  0.000   36.135   48.395
17     HF2 ~1         1     1 .p17.  15.587 1.547 10.077  0.000   12.555   18.619
18  hf_pre ~1         1     1         0.000 0.000     NA     NA    0.000    0.000
19 hf_post ~1         1     1         0.000 0.000     NA     NA    0.000    0.000
33    int1 ~1         2     2 .p14.  46.160 2.931 15.749  0.000   40.415   51.904
34     HF1 ~1         2     2 .p15.  17.176 1.460 11.763  0.000   14.315   20.038
35    int2 ~1         2     2 .p16.  42.265 3.128 13.513  0.000   36.135   48.395
36     HF2 ~1         2     2 .p17.  15.587 1.547 10.077  0.000   12.555   18.619
37  hf_pre ~1         2     2        -6.970 3.653 -1.908  0.056  -14.131    0.190
38 hf_post ~1         2     2       -34.716 5.690 -6.101  0.000  -45.869  -23.564</code></pre>
</div>
</div>
<p><img src="images/pretest-differ.png" class="img-fluid" width="600"></p>
<div id="cell-43" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="28">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">compareFit</span>(hotflash_fit_mg, hotflash_fit_mg2) <span class="sc">|&gt;</span> <span class="fu">summary</span>() <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

                 Df    AIC    BIC  Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)  
hotflash_fit_mg2  2 2899.9 2966.6 1.8271                                        
hotflash_fit_mg   3 2901.5 2965.6 5.3986     3.5715 0.23146       1    0.05878 .
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

####################### Model Fit Indices ###########################
                  chisq df pvalue rmsea    cfi    tli  srmr       aic       bic
hotflash_fit_mg2 1.827†  2   .401 .000† 1.000† 1.006† .041† 2899.894† 2966.567 
hotflash_fit_mg  5.399   3   .145 .129   .986   .944  .088  2901.465  2965.574†

################## Differences in Fit Indices #######################
                                   df rmsea    cfi    tli  srmr   aic    bic
hotflash_fit_mg - hotflash_fit_mg2  1 0.129 -0.014 -0.062 0.047 1.572 -0.993

The following lavaan models were compared:
    hotflash_fit_mg2
    hotflash_fit_mg
To view results, assign the compareFit() output to an object and  use the summary() method; see the class?FitDiff help page.</code></pre>
</div>
</div>
</section>
<section id="두-방식의-비교-test-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="두-방식의-비교-test-assumptions">두 방식의 비교 (Test Assumptions)</h3>
<p>더미 변수 방식과 MG-MACS 방식의 비교</p>
<p>더미 변수 방식의 추정에서 숨은 가정들</p>
<ul>
<li>두 집단 간에 모든 구조가 동일함: factor loading, intercept, residual variance/covariance</li>
<li>Pre-test가 post-test주는 효과도 동일함 (ANCOVA의 가정)</li>
</ul>
<p>이전 더미 변수 방식의 경우:<br>
<img src="images/fig19-16.png" class="img-fluid" width="600"></p>
<div id="cell-45" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="29">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test assumptions</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>hotflash_model_mg3 <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre =~ int1 + HF1</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post =~ int2 + HF2</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post ~ c(a, a)*hf_pre  # 사전 검사가 사후 검사에 동일하게 영향을 미친다고 가정</span></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="st">  HF1 ~~ HF2</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="st">  int1 ~~ int2</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre ~ 0*1  # pretest 동일성 가정</span></span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>hotflash_fit_mg3 <span class="ot">&lt;-</span> <span class="fu">sem</span>(hotflash_model_mg3,</span>
<span id="cb41-14"><a href="#cb41-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> hotflash,</span>
<span id="cb41-15"><a href="#cb41-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">meanstructure =</span> <span class="cn">TRUE</span>,</span>
<span id="cb41-16"><a href="#cb41-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="st">"g"</span>, <span class="co"># factor type</span></span>
<span id="cb41-17"><a href="#cb41-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">group.equal =</span> <span class="fu">c</span>(</span>
<span id="cb41-18"><a href="#cb41-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"loadings"</span>, <span class="st">"intercepts"</span>,</span>
<span id="cb41-19"><a href="#cb41-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"residuals"</span>, <span class="st">"lv.variances"</span>,</span>
<span id="cb41-20"><a href="#cb41-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"residual.covariances"</span></span>
<span id="cb41-21"><a href="#cb41-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb41-22"><a href="#cb41-22" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-46" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="30">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(hotflash_fit_mg3) <span class="sc">|&gt;</span> <span class="fu">subset</span>(op <span class="sc">==</span> <span class="st">"~"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op    rhs block group label   est    se   z pvalue ci.lower ci.upper
5  hf_post  ~ hf_pre     1     1     a 0.487 0.195 2.5  0.012    0.105    0.868
24 hf_post  ~ hf_pre     2     2     a 0.487 0.195 2.5  0.012    0.105    0.868</code></pre>
</div>
</div>
<div id="cell-47" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="31">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(hotflash_fit_mg3) <span class="sc">|&gt;</span> <span class="fu">subset</span>(op <span class="sc">==</span> <span class="st">"~~"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op     rhs block group label     est      se      z pvalue ci.lower ci.upper
6      HF1 ~~     HF2     1     1  .p6.  60.277  10.820  5.571  0.000   39.071   81.484
7     int1 ~~    int2     1     1  .p7. -24.643  55.046 -0.448  0.654 -132.531   83.246
9     int1 ~~    int1     1     1  .p9.  52.755 179.207  0.294  0.768 -298.483  403.993
10     HF1 ~~     HF1     1     1 .p10.  98.604  17.851  5.524  0.000   63.617  133.592
11    int2 ~~    int2     1     1 .p11.  70.300  51.321  1.370  0.171  -30.286  170.887
12     HF2 ~~     HF2     1     1 .p12.  53.415   9.107  5.865  0.000   35.566   71.265
13  hf_pre ~~  hf_pre     1     1 .p13. 349.971 190.043  1.842  0.066  -22.507  722.449
14 hf_post ~~ hf_post     1     1 .p14. 138.752  35.569  3.901  0.000   69.039  208.465
25     HF1 ~~     HF2     2     2  .p6.  60.277  10.820  5.571  0.000   39.071   81.484
26    int1 ~~    int2     2     2  .p7. -24.643  55.046 -0.448  0.654 -132.531   83.246
28    int1 ~~    int1     2     2  .p9.  52.755 179.207  0.294  0.768 -298.483  403.993
29     HF1 ~~     HF1     2     2 .p10.  98.604  17.851  5.524  0.000   63.617  133.592
30    int2 ~~    int2     2     2 .p11.  70.300  51.321  1.370  0.171  -30.286  170.887
31     HF2 ~~     HF2     2     2 .p12.  53.415   9.107  5.865  0.000   35.566   71.265
32  hf_pre ~~  hf_pre     2     2 .p13. 349.971 190.043  1.842  0.066  -22.507  722.449
33 hf_post ~~ hf_post     2     2 .p14. 138.752  35.569  3.901  0.000   69.039  208.465</code></pre>
</div>
</div>
<div id="cell-48" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="32">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(hotflash_fit_mg3) <span class="sc">|&gt;</span> <span class="fu">subset</span>(op <span class="sc">==</span> <span class="st">"~1"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op rhs block group label     est    se      z pvalue ci.lower ci.upper
8   hf_pre ~1         1     1         0.000 0.000     NA     NA    0.000    0.000
15    int1 ~1         1     1 .p15.  42.656 2.048 20.826      0   38.642   46.671
16     HF1 ~1         1     1 .p16.  15.737 1.128 13.949      0   13.525   17.948
17    int2 ~1         1     1 .p17.  40.870 2.349 17.396      0   36.266   45.475
18     HF2 ~1         1     1 .p18.  14.713 1.044 14.088      0   12.666   16.760
19 hf_post ~1         1     1         0.000 0.000     NA     NA    0.000    0.000
27  hf_pre ~1         2     2         0.000 0.000     NA     NA    0.000    0.000
34    int1 ~1         2     2 .p15.  42.656 2.048 20.826      0   38.642   46.671
35     HF1 ~1         2     2 .p16.  15.737 1.128 13.949      0   13.525   17.948
36    int2 ~1         2     2 .p17.  40.870 2.349 17.396      0   36.266   45.475
37     HF2 ~1         2     2 .p18.  14.713 1.044 14.088      0   12.666   16.760
38 hf_post ~1         2     2       -28.615 3.149 -9.087      0  -34.787  -22.444</code></pre>
</div>
</div>
<p>앞서 더미 변수 방식의 결과와 달리 모형 적합도가 매우 좋지 않음!</p>
<ul>
<li>Multi-group 방식에서는 가정들에 대한 검증도 동시에 이루어지고 있음.<br>
</li>
<li>즉, 여기서는 더미 변수 방식의 가정들이 매우 맞지 않음을 확인할 수 있음.</li>
</ul>
<div id="cell-50" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="33">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dummy 방식과의 비교</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">compareFit</span>(hotflash_fit, hotflash_fit_mg3, <span class="at">nested =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span> <span class="fu">summary</span>() <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>####################### Model Fit Indices ###########################
                   chisq df pvalue rmsea   cfi   tli  srmr       aic       bic
hotflash_fit      3.501†  2   .174 .088† .994† .968† .082† 2956.482† 2987.254†
hotflash_fit_mg3 86.416  12   .000 .359  .565  .565  .534  2964.482  3005.512 

The following lavaan models were compared:
    hotflash_fit
    hotflash_fit_mg3
To view results, assign the compareFit() output to an object and  use the summary() method; see the class?FitDiff help page.</code></pre>
</div>
</div>
<div id="cell-51" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="34">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial model과의 비교</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">compareFit</span>(hotflash_fit_mg, hotflash_fit_mg3) <span class="sc">|&gt;</span> <span class="fu">summary</span>()<span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

                 Df    AIC    BIC   Chisq Chisq diff  RMSEA Df diff Pr(&gt;Chisq)    
hotflash_fit_mg   3 2901.5 2965.6  5.3986                                         
hotflash_fit_mg3 12 2964.5 3005.5 86.4155     81.017 0.4083       9  1.015e-13 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

####################### Model Fit Indices ###########################
                   chisq df pvalue rmsea   cfi   tli  srmr       aic       bic
hotflash_fit_mg   5.399†  3   .145 .129† .986† .944† .088† 2901.465† 2965.574†
hotflash_fit_mg3 86.416  12   .000 .359  .565  .565  .534  2964.482  3005.512 

################## Differences in Fit Indices #######################
                                   df rmsea    cfi    tli  srmr    aic    bic
hotflash_fit_mg3 - hotflash_fit_mg  9  0.23 -0.421 -0.379 0.446 63.017 39.938

The following lavaan models were compared:
    hotflash_fit_mg
    hotflash_fit_mg3
To view results, assign the compareFit() output to an object and  use the summary() method; see the class?FitDiff help page.</code></pre>
</div>
</div>
<section id="slopes-vary" class="level4">
<h4 class="anchored" data-anchor-id="slopes-vary">Slopes Vary</h4>
<p>앞의 모형에서 ANCOVA의 가정인 두 집단 간에 pre-test와 post-test의 관계가 동일하다는 가정을 검증함.<br>
즉, 앞의 모든 가정을 포함한 모형에서, 집단 별로 기울기만 다르게 추정하면,</p>
<div id="cell-53" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="35">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Slopes Vary</span></span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>hotflash_model_mg4 <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre =~ int1 + HF1</span></span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post =~ int2 + HF2</span></span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post ~ c(a, b)*hf_pre</span></span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a><span class="st">  HF1 ~~ HF2</span></span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a><span class="st">  int1 ~~ int2</span></span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre ~ 0*1</span></span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb52-13"><a href="#cb52-13" aria-hidden="true" tabindex="-1"></a>hotflash_fit_mg4 <span class="ot">&lt;-</span> <span class="fu">sem</span>(hotflash_model_mg4,</span>
<span id="cb52-14"><a href="#cb52-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> hotflash,</span>
<span id="cb52-15"><a href="#cb52-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">meanstructure =</span> <span class="cn">TRUE</span>,</span>
<span id="cb52-16"><a href="#cb52-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="st">"g"</span>, <span class="co"># factor type</span></span>
<span id="cb52-17"><a href="#cb52-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">group.equal =</span> <span class="fu">c</span>(</span>
<span id="cb52-18"><a href="#cb52-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"loadings"</span>, <span class="st">"intercepts"</span>,</span>
<span id="cb52-19"><a href="#cb52-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"residuals"</span>, <span class="st">"lv.variances"</span>,</span>
<span id="cb52-20"><a href="#cb52-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"residual.covariances"</span></span>
<span id="cb52-21"><a href="#cb52-21" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb52-22"><a href="#cb52-22" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-54" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="36">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">compareFit</span>(hotflash_fit_mg3, hotflash_fit_mg4) <span class="sc">|&gt;</span> <span class="fu">summary</span>() <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

                 Df    AIC    BIC  Chisq Chisq diff  RMSEA Df diff Pr(&gt;Chisq)    
hotflash_fit_mg4 11 2925.3 2968.8 45.194                                         
hotflash_fit_mg3 12 2964.5 3005.5 86.415     41.222 0.9154       1  1.359e-10 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

####################### Model Fit Indices ###########################
                   chisq df pvalue rmsea   cfi   tli  srmr       aic       bic
hotflash_fit_mg4 45.194† 11   .000 .254† .800† .782† .209† 2925.260† 2968.854†
hotflash_fit_mg3 86.416  12   .000 .359  .565  .565  .534  2964.482  3005.512 

################## Differences in Fit Indices #######################
                                    df rmsea    cfi    tli  srmr    aic    bic
hotflash_fit_mg3 - hotflash_fit_mg4  1 0.105 -0.235 -0.217 0.325 39.222 36.658

The following lavaan models were compared:
    hotflash_fit_mg4
    hotflash_fit_mg3
To view results, assign the compareFit() output to an object and  use the summary() method; see the class?FitDiff help page.</code></pre>
</div>
</div>
</section>
</section>
<section id="initial-model-revised" class="level3">
<h3 class="anchored" data-anchor-id="initial-model-revised">Initial Model revised</h3>
<p>Initial 모형의 적합도가 낮은 이유로 인해 더 나은 모형으로 개선<br>
두 집단에서 모두 Cov(int1, int2)가 통계적으로 유의하지 않으므로 0으로 제약<br>
Chi-square가 약간 증가하나 추가 자유도 2 확보</p>
<div id="cell-56" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="37">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(hotflash_fit_mg) <span class="sc">|&gt;</span> <span class="fu">subset</span>(op <span class="sc">==</span> <span class="st">"~~"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op     rhs block group label     est      se      z pvalue ci.lower ci.upper
6      HF1 ~~     HF2     1     1        67.058  18.003  3.725  0.000   31.773  102.344
7     int1 ~~    int2     1     1       -28.916  98.630 -0.293  0.769 -222.227  164.396
9     int1 ~~    int1     1     1       170.287 124.805  1.364  0.172  -74.326  414.900
10     HF1 ~~     HF1     1     1        74.107  19.536  3.793  0.000   35.817  112.397
11    int2 ~~    int2     1     1        39.030 107.473  0.363  0.716 -171.614  249.674
12     HF2 ~~     HF2     1     1        81.674  19.666  4.153  0.000   43.128  120.220
13  hf_pre ~~  hf_pre     1     1       287.136 148.917  1.928  0.054   -4.735  579.008
14 hf_post ~~ hf_post     1     1        68.950  49.956  1.380  0.168  -28.962  166.863
25     HF1 ~~     HF2     2     2        47.191  10.578  4.461  0.000   26.460   67.923
26    int1 ~~    int2     2     2        44.760  37.540  1.192  0.233  -28.817  118.337
28    int1 ~~    int1     2     2       241.229  74.588  3.234  0.001   95.039  387.419
29     HF1 ~~     HF1     2     2        99.551  23.596  4.219  0.000   53.304  145.798
30    int2 ~~    int2     2     2        81.492  25.448  3.202  0.001   31.615  131.368
31     HF2 ~~     HF2     2     2        24.780   5.610  4.417  0.000   13.785   35.775
32  hf_pre ~~  hf_pre     2     2       114.255  70.087  1.630  0.103  -23.113  251.622
33 hf_post ~~ hf_post     2     2         2.901  52.283  0.055  0.956  -99.571  105.373</code></pre>
</div>
</div>
<div id="cell-57" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="38">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Initial 2: remove covariances between int1, int2</span></span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>hotflash_model_mg5 <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre =~ int1 + HF1</span></span>
<span id="cb57-4"><a href="#cb57-4" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post =~ int2 + HF2</span></span>
<span id="cb57-5"><a href="#cb57-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-6"><a href="#cb57-6" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post ~ hf_pre</span></span>
<span id="cb57-7"><a href="#cb57-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-8"><a href="#cb57-8" aria-hidden="true" tabindex="-1"></a><span class="st">  HF1 ~~ HF2</span></span>
<span id="cb57-9"><a href="#cb57-9" aria-hidden="true" tabindex="-1"></a><span class="st">  int1 ~~ 0*int2  # fix the covariance to 0</span></span>
<span id="cb57-10"><a href="#cb57-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb57-11"><a href="#cb57-11" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre ~ 0*1</span></span>
<span id="cb57-12"><a href="#cb57-12" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb57-13"><a href="#cb57-13" aria-hidden="true" tabindex="-1"></a>hotflash_fit_mg5 <span class="ot">&lt;-</span> <span class="fu">sem</span>(hotflash_model_mg5,</span>
<span id="cb57-14"><a href="#cb57-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> hotflash,</span>
<span id="cb57-15"><a href="#cb57-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">meanstructure =</span> <span class="cn">TRUE</span>,</span>
<span id="cb57-16"><a href="#cb57-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="st">"g"</span>, <span class="co"># factor type</span></span>
<span id="cb57-17"><a href="#cb57-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"loadings"</span>, <span class="st">"intercepts"</span>)</span>
<span id="cb57-18"><a href="#cb57-18" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-58" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="39">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">compareFit</span>(hotflash_fit_mg, hotflash_fit_mg5) <span class="sc">|&gt;</span> <span class="fu">summary</span>() <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

                 Df    AIC    BIC  Chisq Chisq diff RMSEA Df diff Pr(&gt;Chisq)
hotflash_fit_mg   3 2901.5 2965.6 5.3986                                    
hotflash_fit_mg5  5 2899.1 2958.1 7.0745     1.6759     0       2     0.4326

####################### Model Fit Indices ###########################
                  chisq df pvalue rmsea   cfi   tli  srmr       aic       bic
hotflash_fit_mg  5.399†  3   .145 .129  .986  .944  .088† 2901.465  2965.574 
hotflash_fit_mg5 7.074   5   .215 .093† .988† .971† .095  2899.141† 2958.121†

################## Differences in Fit Indices #######################
                                   df  rmsea   cfi   tli  srmr    aic    bic
hotflash_fit_mg5 - hotflash_fit_mg  2 -0.036 0.002 0.027 0.006 -2.324 -7.453

The following lavaan models were compared:
    hotflash_fit_mg
    hotflash_fit_mg5
To view results, assign the compareFit() output to an object and  use the summary() method; see the class?FitDiff help page.</code></pre>
</div>
</div>
</section>
<section id="효과에-대한-재검증" class="level3">
<h3 class="anchored" data-anchor-id="효과에-대한-재검증">효과에 대한 재검증</h3>
<section id="no-main-effect" class="level4">
<h4 class="anchored" data-anchor-id="no-main-effect">No Main Effect</h4>
<p>치료의 효과가 없다는 가정: post-test 잠재변수의 intercept를 0으로 제약<br>
(pre-test 잠재변수의 intercept는 0으로 제약되어 있음)</p>
<div id="cell-60" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="40">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># No main effect</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>hotflash_model_mg6 <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre =~ int1 + HF1</span></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post =~ int2 + HF2</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post ~ hf_pre</span></span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="st">  HF1 ~~ HF2</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a><span class="st">  int1 ~~ 0*int2  # fix the covariance to 0</span></span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre ~ 0*1</span></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post ~ 0*1  # fix the intercepts to 0 (아래 group.equal에서 means을 동일하게 제약하는 것과 같은 결과)</span></span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a>hotflash_fit_mg6 <span class="ot">&lt;-</span> <span class="fu">sem</span>(hotflash_model_mg6,</span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> hotflash,</span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">meanstructure =</span> <span class="cn">TRUE</span>,</span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="st">"g"</span>, <span class="co"># factor type</span></span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"loadings"</span>, <span class="st">"intercepts"</span>, </span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"means"</span>) <span class="co"># fix the means to 0</span></span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-61" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="41">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">compareFit</span>(hotflash_fit_mg5, hotflash_fit_mg6) <span class="sc">|&gt;</span> <span class="fu">summary</span>() <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

                 Df    AIC    BIC   Chisq Chisq diff  RMSEA Df diff Pr(&gt;Chisq)    
hotflash_fit_mg5  5 2899.1 2958.1  7.0745                                         
hotflash_fit_mg6  6 2958.8 3015.2 68.7447      61.67 1.1243       1  4.061e-15 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

####################### Model Fit Indices ###########################
                   chisq df pvalue rmsea   cfi   tli  srmr       aic       bic
hotflash_fit_mg5  7.074†  5   .215 .093† .988† .971† .095† 2899.141† 2958.121†
hotflash_fit_mg6 68.745   6   .000 .467  .633  .266  .524  2958.811  3015.227 

################## Differences in Fit Indices #######################
                                    df rmsea    cfi    tli  srmr   aic    bic
hotflash_fit_mg6 - hotflash_fit_mg5  1 0.374 -0.355 -0.705 0.429 59.67 57.106

The following lavaan models were compared:
    hotflash_fit_mg5
    hotflash_fit_mg6
To view results, assign the compareFit() output to an object and  use the summary() method; see the class?FitDiff help page.</code></pre>
</div>
</div>
<div id="cell-62" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="42">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(hotflash_fit_mg5, <span class="at">standardized =</span> <span class="st">"std.all"</span>) <span class="sc">|&gt;</span> <span class="fu">subset</span>(op <span class="sc">==</span> <span class="st">"~1"</span> <span class="sc">&amp;</span> lhs <span class="sc">==</span> <span class="st">"hf_post"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op rhs block group label     est    se      z pvalue ci.lower ci.upper std.all
19 hf_post ~1         1     1         0.000 0.000     NA     NA    0.000    0.000    0.00
38 hf_post ~1         2     2       -28.308 3.143 -9.006      0  -34.468  -22.147   -4.25</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled" title="Effect Size">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Effect Size
</div>
</div>
<div class="callout-body-container callout-body">
<p>두 모형의 큰 차이는 chi-square difference test에서나 post-test의 intercept에 대한 유의성 테스트에서나 동일하게 나타남.<br>
치료 효과의 크기에 대해서는 Int 변수의 metric으로 28.3점 감소한다고 해석할 수 있으나, 표준화하려면 Pre-test의 통제집단과 처치집단의 pooled standard deviation을 사용해야 함; 여러 방식이 제안됨. 논란의 여지가 있음! <a href="https://www.psychometrica.de/effect_size.html">참고</a></p>
<p>즉, cohen’s d = -28.3 / pooled SD = <span class="math inline">\(\displaystyle \frac{-28.3}{\sqrt{\frac{255.7 + 143.7}{2}}} = -2.00\)</span><br>
앞서 더미 변수 방식에서는 Group(Hypnosis) → Post의 회귀계수는 -28.6(비표준화), -1.39(표준화)</p>
<p>참고: HF와 int 측정치의 분산 차이가 매우 크므로, 잠재변수를 구성할 때 effect coding을 사용하면 더 적절한 결과를 얻을 수 있지 않을까… 즉, 요인 부하량의 평균이 1이 되도록 제약해서 두 변수의 영향력을 동등하게 만듦<br>
이 때, 위의 cohen’s d = -1.85로 계산됨</p>
<div class="sourceCode" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>mod <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre =~ NA*a*int1 + b*HF1</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post =~ NA*c*int2 + d*HF2</span></span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a><span class="st">  a + b == 2</span></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a><span class="st">  c + d == 2</span></span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a><span class="st">  ...</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</div>
<div id="cell-64" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="75">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pre-test 잠재변수의 분산 확인</span></span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(hotflash_fit_mg5) <span class="sc">|&gt;</span> <span class="fu">subset</span>(op <span class="sc">==</span> <span class="st">"~~"</span> <span class="sc">&amp;</span> (lhs <span class="sc">==</span> <span class="st">"hf_pre"</span>)) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      lhs op    rhs block group label     est     se     z pvalue ci.lower ci.upper
13 hf_pre ~~ hf_pre     1     1       255.650 97.491 2.622  0.009   64.572  446.727
32 hf_pre ~~ hf_pre     2     2       143.736 60.058 2.393  0.017   26.024  261.449</code></pre>
</div>
</div>
<div id="cell-65" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="36">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(hotflash_fit_mg5) <span class="sc">|&gt;</span> <span class="fu">subset</span>(op <span class="sc">==</span> <span class="st">"~~"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op     rhs block group label     est     se     z pvalue ci.lower ci.upper
6      HF1 ~~     HF2     1     1        64.439 15.850 4.066  0.000   33.373   95.505
7     int1 ~~    int2     1     1         0.000  0.000    NA     NA    0.000    0.000
9     int1 ~~    int1     1     1       200.813 65.273 3.076  0.002   72.880  328.747
10     HF1 ~~     HF1     1     1        70.829 16.758 4.226  0.000   37.983  103.674
11    int2 ~~    int2     1     1        62.914 75.243 0.836  0.403  -84.560  210.388
12     HF2 ~~     HF2     1     1        79.187 17.862 4.433  0.000   44.179  114.196
13  hf_pre ~~  hf_pre     1     1       255.650 97.491 2.622  0.009   64.572  446.727
14 hf_post ~~ hf_post     1     1        70.303 49.163 1.430  0.153  -26.054  166.660
25     HF1 ~~     HF2     2     2        46.821 10.332 4.532  0.000   26.571   67.072
26    int1 ~~    int2     2     2         0.000  0.000    NA     NA    0.000    0.000
28    int1 ~~    int1     2     2       206.182 65.952 3.126  0.002   76.918  335.447
29     HF1 ~~     HF1     2     2        96.979 23.606 4.108  0.000   50.712  143.247
30    int2 ~~    int2     2     2        68.308 20.877 3.272  0.001   27.389  109.227
31     HF2 ~~     HF2     2     2        23.690  5.445 4.351  0.000   13.018   34.362
32  hf_pre ~~  hf_pre     2     2       143.736 60.058 2.393  0.017   26.024  261.449
33 hf_post ~~ hf_post     2     2        39.097 22.874 1.709  0.087   -5.735   83.930</code></pre>
</div>
</div>
</section>
<section id="no-interaction-effect" class="level4">
<h4 class="anchored" data-anchor-id="no-interaction-effect">No Interaction Effect</h4>
<p>앞서 Slopes differs에서처럼 pretest → posttest의 관계가 집단에 따라 동일하다고 가정하면,<br>
즉, no slope difference를 가정</p>
<div id="cell-67" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="37">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># No slope difference: interaction</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a>hotflash_model_mg7 <span class="ot">&lt;-</span> <span class="st">"</span></span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre =~ int1 + HF1</span></span>
<span id="cb70-4"><a href="#cb70-4" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post =~ int2 + HF2</span></span>
<span id="cb70-5"><a href="#cb70-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-6"><a href="#cb70-6" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_post ~ c(a, a)*hf_pre</span></span>
<span id="cb70-7"><a href="#cb70-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-8"><a href="#cb70-8" aria-hidden="true" tabindex="-1"></a><span class="st">  HF1 ~~ HF2</span></span>
<span id="cb70-9"><a href="#cb70-9" aria-hidden="true" tabindex="-1"></a><span class="st">  int1 ~~ 0*int2  # fix the covariance to 0</span></span>
<span id="cb70-10"><a href="#cb70-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb70-11"><a href="#cb70-11" aria-hidden="true" tabindex="-1"></a><span class="st">  hf_pre ~ 0*1</span></span>
<span id="cb70-12"><a href="#cb70-12" aria-hidden="true" tabindex="-1"></a><span class="st">"</span></span>
<span id="cb70-13"><a href="#cb70-13" aria-hidden="true" tabindex="-1"></a>hotflash_fit_mg7 <span class="ot">&lt;-</span> <span class="fu">sem</span>(hotflash_model_mg7,</span>
<span id="cb70-14"><a href="#cb70-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> hotflash,</span>
<span id="cb70-15"><a href="#cb70-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">meanstructure =</span> <span class="cn">TRUE</span>,</span>
<span id="cb70-16"><a href="#cb70-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">group =</span> <span class="st">"g"</span>, <span class="co"># factor type</span></span>
<span id="cb70-17"><a href="#cb70-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">group.equal =</span> <span class="fu">c</span>(<span class="st">"loadings"</span>, <span class="st">"intercepts"</span>)</span>
<span id="cb70-18"><a href="#cb70-18" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div id="cell-68" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="38">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">compareFit</span>(hotflash_fit_mg5, hotflash_fit_mg7) <span class="sc">|&gt;</span> <span class="fu">summary</span>() <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>################### Nested Model Comparison #########################

Chi-Squared Difference Test

                 Df    AIC    BIC   Chisq Chisq diff   RMSEA Df diff Pr(&gt;Chisq)    
hotflash_fit_mg5  5 2899.1 2958.1  7.0745                                          
hotflash_fit_mg7  6 2913.0 2969.5 22.9747       15.9 0.55716       1  6.677e-05 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

####################### Model Fit Indices ###########################
                   chisq df pvalue rmsea   cfi   tli  srmr       aic       bic
hotflash_fit_mg5  7.074†  5   .215 .093† .988† .971† .095† 2899.141† 2958.121†
hotflash_fit_mg7 22.975   6   .001 .243  .901  .801  .113  2913.041  2969.457 

################## Differences in Fit Indices #######################
                                    df rmsea    cfi    tli  srmr  aic    bic
hotflash_fit_mg7 - hotflash_fit_mg5  1  0.15 -0.087 -0.169 0.018 13.9 11.336

The following lavaan models were compared:
    hotflash_fit_mg5
    hotflash_fit_mg7
To view results, assign the compareFit() output to an object and  use the summary() method; see the class?FitDiff help page.</code></pre>
</div>
</div>
<div id="cell-69" class="cell" data-vscode="{&quot;languageId&quot;:&quot;r&quot;}" data-execution_count="39">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parameterEstimates</span>(hotflash_fit_mg5, <span class="at">standardized=</span><span class="st">"std.all"</span>) <span class="sc">|&gt;</span> <span class="fu">subset</span>(op <span class="sc">==</span> <span class="st">"~"</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       lhs op    rhs block group label    est    se      z pvalue ci.lower ci.upper
5  hf_post  ~ hf_pre     1     1        1.169 0.271  4.315  0.000    0.638    1.700
24 hf_post  ~ hf_pre     2     2       -0.191 0.197 -0.972  0.331   -0.577    0.195
   std.all
5    0.912
24  -0.345</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>통제집단에서만 사전검사에서 높은 열감을 보고한 여성이 사후검사도 높은 열감을 보이는 상관관계(0.912)를 보임.<br>
치료집단에서는 사전검사 수치가 사후검사에 영향을 주지 않는 것으로 보임.</p>
<p>즉, 사전검사와 어느 집단에 속하는지가 서로 상호작용하여 사후검사에 효과가 나타났음; interaction effect</p>
</div>
</div>
<!-- ## Latent Change Score Model

![](images/latent-change-model.png){width=700} -->


</section>
</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/sem\.modellings\.art");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
          // target, if specified
          link.setAttribute("target", "_blank");
          if (link.getAttribute("rel") === null) {
            link.setAttribute("rel", "noopener");
          }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../contents/chap18.html" class="pagination-link" aria-label="Multigroup Models">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Multigroup Models</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../contents/chap21.html" class="pagination-link" aria-label="Latent Growth Models">
        <span class="nav-page-text">Latent Growth Models</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>This work © 2024 by Sungkyun Cho is licensed under CC BY-NC-SA 4.0</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>